name: Unzip Archive

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          rm -rf extracted-folder
          mkdir extracted-folder
          unzip -o "silah-e-khair-foundation.zip" -d extracted-folder

      - name: Remove nested Git files
        run: |
          rm -rf extracted-folder/.git

      - name: Move project to repository root
        run: |
          cp -r extracted-folder/. .
          rm -rf extracted-folder

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Extract project from ZIP" || exit 0
          git push
